name: CI

on:
#  push:
#    branches: [ main, develop ]
#  pull_request:
#    branches: [ main, develop ]
   workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install pyjwt  # For provenance testing
        
    - name: Run tests
      run: |
        pytest tests/ -v --junitxml=test-results.xml
        
    - name: Check style
      run: |
        flake8 .
        black . --check
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results.xml

    # Test release workflow
    - name: Test release workflow
      if: github.event_name == 'pull_request'
      run: |
        # Simulate JSON file creation
        mkdir -p json
        cp data/output/Nano\ Di\ Side.pca.json json/
        
        # Test provenance generation
        gh workflow run release.yml 

    - name: Install SLSA verifier
      if: github.event_name == 'pull_request'
      run: |
        mkdir -p $HOME/.local/bin
        wget -O $HOME/.local/bin/slsa-verifier https://github.com/slsa-framework/slsa-verifier/releases/download/v2.0.0/slsa-verifier-linux-amd64
        chmod +x $HOME/.local/bin/slsa-verifier
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Verify SLSA Provenance
      if: github.event_name == 'pull_request'
      run: |
        slsa-verifier verify-artifact \
          --provenance-path provenance.att \
          --source-uri "github.com/${{ github.repository }}" \
          --source-tag "${{ github.ref }}" 
