name: Combine Data Files

on:
  workflow_dispatch:
    inputs:
      file1:
        description: 'First filename (without extension)'
        required: true
      type1:
        description: 'First file type (pca/pcj/pcp/pcr/vgl)'
        required: true
        type: choice
        options:
          - pca
          - pcj
          - pcp
          - pcr
          - vgl
      file2:
        description: 'Second filename (without extension)'
        required: false
      type2:
        description: 'Second file type (pca/pcj/pcp/pcr/vgl)'
        required: false
        type: choice
        options:
          - none
          - pca
          - pcj
          - pcp
          - pcr
          - vgl
        default: 'none'
      file3:
        description: 'Third filename (without extension)'
        required: false
      type3:
        description: 'Third file type (pca/pcj/pcp/pcr/vgl)'
        required: false
        type: choice
        options:
          - none
          - pca
          - pcj
          - pcp
          - pcr
          - vgl
        default: 'none'

jobs:
  combine-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas tabulate
    
    - name: Create input file
      run: |
        echo '${{ github.event.inputs.file1 }}|${{ github.event.inputs.type1 }}' > input_files.txt
        if [ "${{ github.event.inputs.type2 }}" != "none" ]; then
          echo '${{ github.event.inputs.file2 }}|${{ github.event.inputs.type2 }}' >> input_files.txt
        fi
        if [ "${{ github.event.inputs.type3 }}" != "none" ]; then
          echo '${{ github.event.inputs.file3 }}|${{ github.event.inputs.type3 }}' >> input_files.txt
        fi
    
    - name: Combine data
      run: python .github/scripts/data_combiner.py data/output/combined_analysis.md input_files.txt
    
    - name: Commit combined analysis
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        git add data/output/combined_analysis.md
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update combined analysis [skip ci]"
          git push
        fi
