name: File Processor

on:
  push:
    paths:
      - 'data/input/*.pca'
      - 'json/*.json'
  workflow_dispatch:
    inputs:
      filename:
        description: 'File to process'
        required: true
        default: 'Nano Di Side.pca'

permissions:
  contents: write
  id-token: write
  actions: read
  attestations: write

jobs:
  process-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Process File
      id: process
      run: |
        mkdir -p data/output
        
        if [[ "${{ github.event.inputs.filename }}" == *.pca ]]; then
          INPUT_FILE="data/input/${{ github.event.inputs.filename }}"
          OUTPUT_NAME=$(basename "${{ github.event.inputs.filename }}" .pca).pca.json
          python3 .github/scripts/pca_to_json.py "$INPUT_FILE"
          echo "filename=data/output/$OUTPUT_NAME" >> $GITHUB_OUTPUT
        else
          echo "filename=${{ github.event.inputs.filename }}" >> $GITHUB_OUTPUT
        fi

    - name: Generate Attestation
      id: attest
      uses: actions/attest@v2.1.0
      with:
        subject-path: ${{ steps.process.outputs.filename }}
        predicate-type: 'https://in-toto.io/attestation/release/v0.1'
        predicate: |
          {
            "purl": "pkg:github/${{ github.repository }}",
            "version": "${{ github.sha }}",
            "metadata": {
              "buildInvocationId": "${{ github.run_id }}",
              "completeness": {
                "parameters": true,
                "environment": true,
                "materials": true
              }
            }
          }

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: scan-${{ github.run_number }}
        name: "Scan: ${{ steps.process.outputs.filename }}"
        body: |
          Processed file: ${{ steps.process.outputs.filename }}
          Attestation: ${{ steps.attest.outputs.attestation-url }}
        files: |
          ${{ steps.process.outputs.filename }}
          ${{ steps.attest.outputs.bundle-path }}
