name: File Processor

on:
  push:
    paths:
      - 'data/input/*.pca'
      - 'json/*.json'
  workflow_dispatch:
    inputs:
      filename:
        description: 'File to process'
        required: true
        default: 'Nano Di Side.pca'

permissions:
  contents: write
  id-token: write
  actions: read
  attestations: write

jobs:
  process-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install SLSA verifier
      run: |
        mkdir -p $HOME/.local/bin
        wget -O $HOME/.local/bin/slsa-verifier https://github.com/slsa-framework/slsa-verifier/releases/download/v2.0.0/slsa-verifier-linux-amd64
        chmod +x $HOME/.local/bin/slsa-verifier
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Process File
      id: process
      run: |
        mkdir -p data/output
        
        if [[ "${{ github.event.inputs.filename }}" == *.pca ]]; then
          INPUT_FILE="data/input/${{ github.event.inputs.filename }}"
          OUTPUT_NAME=$(basename "${{ github.event.inputs.filename }}" .pca).pca.json
          python3 .github/scripts/pca_to_json.py "$INPUT_FILE"
          OUTPUT_PATH="$(pwd)/data/output/$OUTPUT_NAME"
          echo "filename=$OUTPUT_NAME" >> $GITHUB_OUTPUT
          echo "filepath=$OUTPUT_PATH" >> $GITHUB_OUTPUT
        else
          FULL_PATH="$(pwd)/${{ github.event.inputs.filename }}"
          echo "filename=${{ github.event.inputs.filename }}" >> $GITHUB_OUTPUT
          echo "filepath=$FULL_PATH" >> $GITHUB_OUTPUT
        fi

    - name: Debug File Path
      run: |
        echo "Current directory: $(pwd)"
        echo "File path from output: ${{ steps.process.outputs.filepath }}"
        echo "Directory contents:"
        ls -la data/output/
        echo "File exists check:"
        test -f "${{ steps.process.outputs.filepath }}" && echo "File exists" || echo "File does not exist"
        echo "File contents preview:"
        head -n 5 "${{ steps.process.outputs.filepath }}" || echo "Could not read file"

    - name: Verify File for Attestation
      run: |
        echo "Verifying file at: ${{ steps.process.outputs.filepath }}"
        ls -l "${{ steps.process.outputs.filepath }}"
        echo "File contents:"
        cat "${{ steps.process.outputs.filepath }}"

    - name: Generate Attestation
      id: attest
      uses: actions/attest@v2.1.0
      with:
        subject-path: ${{ steps.process.outputs.filepath }}
        predicate-type: 'https://in-toto.io/attestation/release/v0.1'
        predicate: |
          {
            "purl": "pkg:github/${{ github.repository }}",
            "version": "${{ github.sha }}",
            "metadata": {
              "buildInvocationId": "${{ github.run_id }}",
              "completeness": {
                "parameters": true,
                "environment": true,
                "materials": true
              }
            }
          }

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: scan-${{ github.run_number }}
        name: "Scan: ${{ steps.process.outputs.filename }}"
        body: |
          Processed file: ${{ steps.process.outputs.filename }}
          Attestation: ${{ steps.attest.outputs.attestation-url }}
        files: |
          ${{ steps.process.outputs.filepath }}
          ${{ steps.attest.outputs.bundle-path }}
