name: File Processor

on:
  push:
    paths:
      - 'data/input/*.pca'
      - 'json/*.json'
  workflow_dispatch:
    inputs:
      filename:
        description: 'File to process'
        required: true
        default: 'Nano Di Side.pca'

permissions:
  contents: write
  id-token: write
  actions: read
  security-events: write
  packages: write

jobs:
  process-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Process File
      id: process
      run: |
        if [[ "${{ github.event.inputs.filename }}" == *.pca ]]; then
          python3 pca_parser.py "${{ github.event.inputs.filename }}"
          echo "filename=${github.event.inputs.filename%.pca}.json" >> $GITHUB_OUTPUT
        else
          echo "filename=${{ github.event.inputs.filename }}" >> $GITHUB_OUTPUT
        fi

    - name: Generate Attestation
      uses: actions/attest@v2.1.0
      with:
        predicate-type: 'https://slsa.dev/provenance/v1'
        predicate: |
          {
            "buildType": "https://github.com/actions/runner",
            "builder": {
              "id": "${{ github.repository }}/.github/workflows/file-processor.yml@${{ github.ref }}"
            }
          }
        subject-path: ${{ steps.process.outputs.filename }}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.process.outputs.filename }}
        name: "Scan ${{ steps.process.outputs.filename }}"
        files: |
          ${{ steps.process.outputs.filename }}
          provenance.att
