name: PCA Converter and Release

on:
  push:
    paths:
      - 'data/input/*.pca'
  workflow_dispatch:
    inputs:
      pca_file:
        description: 'PCA file to convert'
        required: true
        default: 'Nano Di Side.pca'

permissions:
  contents: write
  id-token: write
  actions: read
  security-events: write
  packages: write

jobs:
  convert-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Convert PCA to JSON
      run: |
        python3 pca_parser.py "${{ github.event.inputs.pca_file || github.event.path }}"
        echo "json_file=${pca_file%.pca}.json" >> $GITHUB_ENV

    - name: Generate SLSA Provenance
      uses: slsa-framework/slsa-github-generator/actions/generator@v1.9.0
      with:
        base64-subjects: "${{ hashFiles(env.json_file) }}"
        provenance-name: "provenance.att"
        upload-assets: true

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.json_file }}
        release_name: "Scan ${{ env.json_file }}"
        body: |
          Converted from PCA file: ${{ github.event.inputs.pca_file || github.event.path }}
          See attached provenance for build verification.
        draft: false
        prerelease: false
